name: Manual Test Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod

      version:
        description: "Enter Version"
        required: true
        default: "1.0.0"

      service:
        description: "Enter Service Name"
        required: true
        default: "my-app"

      actiontype:
        description: "Choose Action"
        required: true
        type: choice
        options:
          - deploy
          - restart
          - rollback

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Print Repo Details
        run: |
          echo "Repository Name : $GITHUB_REPOSITORY"
          echo "Branch Name     : $GITHUB_REF_NAME"
          echo "Commit ID       : $GITHUB_SHA"
          echo "Actor Name      : $GITHUB_ACTOR"
          echo "Workflow Name   : $GITHUB_WORKFLOW"
          echo "Run Number      : $GITHUB_RUN_NUMBER"
          echo "Workspace Path  : $GITHUB_WORKSPACE"

      - name: Show User Inputs
        run: |
          echo "Environment : ${{ github.event.inputs.environment }}"
          echo "Version     : ${{ github.event.inputs.version }}"
          echo "Service     : ${{ github.event.inputs.service }}"
          echo "Action      : ${{ github.event.inputs.actiontype }}"

      - name: Show Repo Files
        run: |
          pwd
          ls -la
